services:
  postgresql:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    volumes:
      - .:/usr/src/app
    container_name: api
    restart: always
    ports:
      - 3000:80
    env_file: .env
    depends_on:
      postgresql:
        condition: service_started

volumes:
  postgres_data: # Define um volume para persistência
