services:
  postgresql:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis_cache
    command: redis-server --requirepass ${REDIS_PASSWORD} --user default on >${REDIS_PASSWORD} ~* +@all
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  api:
    build: .
    volumes:
      - .:/usr/src/app
    container_name: api
    restart: always
    ports:
      - 3000:80
    env_file: .env
    depends_on:
      postgresql:
        condition: service_started
      redis:
        condition: service_started

volumes:
  postgres_data:
  redis_data:
