version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}          
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB} 
    ports:
      - "5432:5432"                       # Mapeia a porta 5432 do container para a porta 5432 da máquina host
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persiste os dados do banco de dados

volumes:
  postgres_data:                        # Define um volume para persistência
